### ISSUE TITLE
it loads indefinitely now

### ISSUE THREAD

**Issue by etha-tren** [KRLW890/jevil-simulator#12]
I dont now what happened but your newest update makes it unplayable for some reason I'm using a chromebook ;_;

**Comment by AcidArmy** [comment]
Here's my working fork.
https://acidarmy.github.io/jevil-simulator/

**Comment by VGHOST21** [comment]
If only the guy that made the Bad time simulator helped out with this
project xD

**Comment by AcidArmy** [comment]
Please close this issue. The problem has been resolved.
