### ISSUE TITLE
its not working 

### ISSUE THREAD

**Issue by sonicstar987** [KRLW890/jevil-simulator#13]
so when i came to github to see if there is anything new for jevil simulator new things keep happening well sometimes but now every time i go on the jevil simulator im left with a please wait text and thats all

**Comment by VGHOST21** [comment]
https://acidarmy.github.io/jevil-simulator/

**Comment by AcidArmy** [comment]
Please close this issue. The problem has been resolved.

**Comment by samsamson33** [comment]
This is a WIP, so it isn't fully functional yet.
